/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FSeP32sV5ez
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Work_Sans } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

work_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

'use client'

import { useState } from "react"
import { UploadForm } from "./upload-form";
import { Progress } from "../ui/progress";

export function LandingPage() {
  const [loading, setLoading] = useState<Boolean>(false);

  const uploadFile = (file: File) => {
    setLoading(true);
  }

  return (
    <div className="flex flex-col min-h-[100dvh] items-center justify-center bg-background px-4 py-12 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-md w-full space-y-4 text-center">
        <h1 className="text-3xl font-bold tracking-tighter text-foreground sm:text-4xl md:text-5xl">
          Create an anagram
        </h1>
        <p className="text-muted-foreground md:text-xl">Rewrite some signs, nerd</p>
        {!loading && (
          <UploadForm onSubmit={uploadFile} />
        )}
        {loading && (
          <Progress 
            value={30}
          />
        )}
      </div>
    </div>
  )
}
