/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/FSeP32sV5ez
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Work_Sans } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

work_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

'use client'

import { useState } from "react"
import { UploadForm } from "./upload-form";
import { Progress } from "../ui/progress";

export function LandingPage() {
  const [loading, setLoading] = useState<Boolean>(false);
  const [error, setError] = useState<String>();
  const [results, setResults] = useState<String[]>([]);

  const uploadFile = async (file: File) => {
    setLoading(true);
    setResults([]);

    let fileData = null
    try {
      fileData = await base64EncodeFile(file)
    } catch(error) {
      console.error(error);
      return;
    }

    const response = await fetch("/.netlify/functions/upload-text", {
      method: "POST",
      body: JSON.stringify({
        filename: file.name,
        filetype: file.type,
        filedata: fileData
      })
    })
    const text = await response.text();
    setResults(text.split('\n'));
    setLoading(false);
  }
  
  const base64EncodeFile = (file: File) => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.readAsDataURL(file);
      reader.onload = () => {
        resolve(reader.result);
      }
      reader.onerror = reject;
    })
  }

  return (
    <div className="flex flex-col min-h-[100dvh] items-center justify-center bg-background px-4 py-12 sm:px-6 lg:px-8">
      <div className="mx-auto max-w-md w-full space-y-4 text-center">
        <h1 className="text-3xl font-bold tracking-tighter text-foreground sm:text-4xl md:text-5xl">
          Create an anagram
        </h1>
        <p className="text-muted-foreground md:text-xl">Rewrite some signs, nerd</p>
        {!loading && (
          <UploadForm onSubmit={uploadFile} />
        )}
        {results && (
          <ul>
            {results.map((res, i) => <li key={i}>{res}</li>)}
          </ul>
        )}
        {loading && (
          <Progress 
            value={30}
          />
        )}
      </div>
    </div>
  )
}
